use base64::{engine::general_purpose::STANDARD, Engine}; use serde::{Deserialize,Serialize}; use serde_json::{json,Value}; use std::{io::{BufRead,BufReader,Write},process::{Command,Stdio},sync::{Mutex,OnceLock}}; use tauri::Emitter;
#[derive(Serialize)] #[serde(rename_all="camelCase")] struct HardwareStatus{gpu_name:String,vram_total_mb:Option<u64>,vram_free_mb:Option<u64>,nvidia_available:bool,engine_state:String}
#[derive(Deserialize)] #[serde(rename_all="camelCase")] struct GenerateRequest{prompt:String,width:u32,height:u32,steps:u32,seed:i64,true_cfg_scale:f64,negative_prompt:Option<String>,input_data_url:Option<String>}
#[derive(Serialize)] #[serde(rename_all="camelCase")] struct GenerateResult{image_data_url:String,path:String,seed:i64,elapsed_seconds:f64,width:u32,height:u32}
#[tauri::command] fn hardware_status()->HardwareStatus{let o=Command::new("nvidia-smi").args(["--query-gpu=name,memory.total,memory.free","--format=csv,noheader,nounits"]).output();if let Ok(o)=o{if o.status.success(){let t=String::from_utf8_lossy(&o.stdout);if let Some(l)=t.lines().next(){let p:Vec<_>=l.split(',').map(str::trim).collect();return HardwareStatus{gpu_name:p.first().unwrap_or(&"NVIDIA GPU").to_string(),vram_total_mb:p.get(1).and_then(|v|v.parse().ok()),vram_free_mb:p.get(2).and_then(|v|v.parse().ok()),nvidia_available:true,engine_state:"runtime-ready".into()}}}}HardwareStatus{gpu_name:"未偵測到 NVIDIA GPU".into(),vram_total_mb:None,vram_free_mb:None,nvidia_available:false,engine_state:"hardware-unavailable".into()}}
fn python()->String{std::env::var("AI_STUDIO_PYTHON").unwrap_or_else(|_|if cfg!(windows){"python".into()}else{"python3".into()})}
fn project_root()->std::path::PathBuf{std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().expect("src-tauri must have a parent").to_path_buf()}
#[derive(Clone,Serialize)] #[serde(rename_all="camelCase")] struct EngineProgress{request_id:String,state:String}
struct EngineProcess{child:std::process::Child,stdin:std::process::ChildStdin,stdout:BufReader<std::process::ChildStdout>,stderr_log:std::sync::Arc<Mutex<Vec<String>>>}
static ENGINE_PROCESS:OnceLock<Mutex<Option<EngineProcess>>>=OnceLock::new();
fn engine_process()->&'static Mutex<Option<EngineProcess>>{ENGINE_PROCESS.get_or_init(||Mutex::new(None))}
fn start_engine()->Result<EngineProcess,String>{
 let py=python();let mut child=Command::new(&py).arg(project_root().join("engine/main.py")).current_dir(project_root()).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().map_err(|e|format!("無法啟動 AI Engine ({py}): {e}"))?;
 let stdin=child.stdin.take().ok_or("AI Engine stdin unavailable")?;let stdout=child.stdout.take().ok_or("AI Engine stdout unavailable")?;let stderr=child.stderr.take().ok_or("AI Engine stderr unavailable")?;
 let stderr_log=std::sync::Arc::new(Mutex::new(Vec::<String>::new()));let stderr_copy=stderr_log.clone();
 std::thread::spawn(move||{let mut reader=BufReader::new(stderr);let mut chunk=Vec::new();loop{chunk.clear();match reader.read_until(b'\r',&mut chunk){Ok(0)=>break,Ok(_)=>{let line=String::from_utf8_lossy(&chunk).trim_matches(['\r','\n']).to_string();if !line.is_empty(){eprintln!("[AI Engine] {line}");if let Ok(mut log)=stderr_copy.lock(){log.push(line);if log.len()>80{log.remove(0);}}}},Err(_)=>break}}});
 let mut process=EngineProcess{child,stdin,stdout:BufReader::new(stdout),stderr_log};let mut line=String::new();process.stdout.read_line(&mut line).map_err(|e|format!("讀取 AI Engine ready 失敗: {e}"))?;let ready:Value=serde_json::from_str(line.trim()).map_err(|e|format!("AI Engine ready 格式錯誤: {e}: {line}"))?;if ready["event"]!="ready"{return Err(format!("AI Engine 未進入 ready 狀態: {line}"))}Ok(process)
}
fn generate_image_blocking(app:tauri::AppHandle,request:GenerateRequest)->Result<GenerateResult,String>{
 let id=format!("desktop-generate-{}",std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_err(|e|e.to_string())?.as_millis());
 let path=std::env::temp_dir().join(format!("{id}.png"));let input_path=if let Some(data)=request.input_data_url.as_deref(){let raw=data.split_once(",").map(|x|x.1).unwrap_or(data);let bytes=STANDARD.decode(raw).map_err(|e|format!("輸入圖片格式錯誤: {e}"))?;let p=std::env::temp_dir().join(format!("{id}-input.png"));std::fs::write(&p,bytes).map_err(|e|e.to_string())?;Some(p)}else{None};
 let msg=json!({"id":id,"command":"generate","payload":{"prompt":request.prompt,"width":request.width,"height":request.height,"steps":request.steps,"seed":request.seed,"true_cfg_scale":request.true_cfg_scale,"negative_prompt":request.negative_prompt,"input_path":input_path.as_ref().map(|p|p.to_string_lossy().to_string()),"output_path":path.to_string_lossy()}});
 let mut guard=engine_process().lock().map_err(|_|"AI Engine lock poisoned".to_string())?;if guard.is_none(){*guard=Some(start_engine()?)}let engine=guard.as_mut().ok_or("AI Engine unavailable")?;
 writeln!(engine.stdin,"{}",msg).map_err(|e|format!("傳送生成請求失敗: {e}"))?;engine.stdin.flush().map_err(|e|e.to_string())?;
 let data=loop{let mut line=String::new();let n=engine.stdout.read_line(&mut line).map_err(|e|format!("讀取 AI Engine 失敗: {e}"))?;if n==0{let status=engine.child.try_wait().ok().flatten().map(|s|s.to_string()).unwrap_or_else(||"stdout-closed".into());let stderr=engine.stderr_log.lock().map(|v|v.join("\n")).unwrap_or_default();*guard=None;return Err(format!("AI Engine 意外結束 ({status}).{}",if stderr.is_empty(){" 沒有捕捉到 stderr。".to_string()}else{format!("\n{stderr}")}))}let Ok(v)=serde_json::from_str::<Value>(line.trim())else{continue};if v["request_id"]!=id{continue}match v["event"].as_str(){Some("progress")=>{let state=v["data"]["state"].as_str().unwrap_or("working").to_string();let _=app.emit("engine-progress",EngineProgress{request_id:id.clone(),state});},Some("completed")=>break v["data"].clone(),Some("error")=>return Err(v["data"]["message"].as_str().unwrap_or("AI Engine generation failed").to_string()),_=>{} }};
 drop(guard);let bytes=std::fs::read(&path).map_err(|e|format!("讀取生成圖片失敗: {e}"))?;let _=std::fs::remove_file(&path);if let Some(p)=input_path{let _=std::fs::remove_file(p);}
 Ok(GenerateResult{image_data_url:format!("data:image/png;base64,{}",STANDARD.encode(bytes)),path:data["path"].as_str().unwrap_or_default().into(),seed:data["seed"].as_i64().unwrap_or(request.seed),elapsed_seconds:data["elapsedSeconds"].as_f64().unwrap_or_default(),width:data["width"].as_u64().unwrap_or(request.width as u64) as u32,height:data["height"].as_u64().unwrap_or(request.height as u64) as u32})
}
#[tauri::command] async fn generate_image(app:tauri::AppHandle,request:GenerateRequest)->Result<GenerateResult,String>{tauri::async_runtime::spawn_blocking(move||generate_image_blocking(app,request)).await.map_err(|e|format!("AI Engine 工作失敗: {e}"))?}
#[derive(Serialize, Deserialize)] #[serde(rename_all="camelCase")] struct ModelStatus{id:String,name:String,model_id:String,path:String,installed:bool,size_bytes:u64}
#[derive(Clone,Serialize,Default)] #[serde(rename_all="camelCase")] struct ModelDownloadState{active:bool,phase:String,downloaded_bytes:u64,total_bytes:u64,percent:Option<f64>,message:Option<String>}
static MODEL_DOWNLOAD_STATE:OnceLock<Mutex<ModelDownloadState>>=OnceLock::new();
fn download_state()->&'static Mutex<ModelDownloadState>{MODEL_DOWNLOAD_STATE.get_or_init(||Mutex::new(ModelDownloadState::default()))}
fn set_download_state(app:&tauri::AppHandle,state:ModelDownloadState){if let Ok(mut s)=download_state().lock(){*s=state.clone();}let _=app.emit("model-download-progress",&state);}
#[tauri::command] fn model_download_status()->ModelDownloadState{download_state().lock().map(|s|s.clone()).unwrap_or_default()}
fn parse_model(v:&Value)->Result<ModelStatus,String>{if !v["ok"].as_bool().unwrap_or(false){return Err(v["error"].as_str().unwrap_or("模型管理失敗").into())}serde_json::from_value(v["model"].clone()).map_err(|e|e.to_string())}
fn model_action(action:&str)->Result<ModelStatus,String>{let py=python();let out=Command::new(&py).arg(project_root().join("engine/model_manager.py")).arg(action).current_dir(project_root()).output().map_err(|e|format!("無法啟動模型管理器 ({py}): {e}"))?;let stdout=String::from_utf8_lossy(&out.stdout).trim().to_string();let stderr=String::from_utf8_lossy(&out.stderr).trim().to_string();if stdout.is_empty(){return Err(format!("模型管理器沒有回傳資料。Python: {py}\n{}",if stderr.is_empty(){format!("Process exit: {}",out.status)}else{stderr}))}let line=stdout.lines().rev().find(|l|l.trim_start().starts_with('{')).unwrap_or(&stdout);let v:Value=serde_json::from_str(line.trim()).map_err(|e|format!("模型管理器回傳格式錯誤: {e}\nstdout: {stdout}\nstderr: {stderr}"))?;parse_model(&v)}
fn install_model_stream(app:tauri::AppHandle)->Result<ModelStatus,String>{set_download_state(&app,ModelDownloadState{active:true,phase:"starting".into(),..Default::default()});let py=python();let mut child=Command::new(&py).arg(project_root().join("engine/model_manager.py")).arg("install").current_dir(project_root()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().map_err(|e|format!("無法啟動模型管理器 ({py}): {e}"))?;let stdout=child.stdout.take().ok_or("模型管理器 stdout unavailable")?;let mut final_value:Option<Value>=None;for line in BufReader::new(stdout).lines(){let line=line.map_err(|e|e.to_string())?;if let Ok(v)=serde_json::from_str::<Value>(&line){match v["event"].as_str(){Some("progress")=>set_download_state(&app,ModelDownloadState{active:true,phase:"downloading".into(),downloaded_bytes:v["downloadedBytes"].as_u64().unwrap_or(0),total_bytes:v["totalBytes"].as_u64().unwrap_or(0),percent:v["percent"].as_f64(),message:None}),Some("manifest")=>{if let Ok(mut state)=download_state().lock(){state.total_bytes=v["totalBytes"].as_u64().unwrap_or(state.total_bytes);let copy=state.clone();drop(state);let _=app.emit("model-download-progress",&copy);}},Some("metadata-error")=>{if let Ok(mut state)=download_state().lock(){state.message=v["message"].as_str().map(str::to_owned);}},_=>{if v.get("ok").is_some(){final_value=Some(v);}}}}}let out=child.wait_with_output().map_err(|e|e.to_string())?;let stderr=String::from_utf8_lossy(&out.stderr).trim().to_string();let v=match final_value{Some(v)=>v,None=>{let msg=format!("模型管理器沒有回傳完成資料。{}",if stderr.is_empty(){String::new()}else{format!("\n{stderr}")});set_download_state(&app,ModelDownloadState{active:false,phase:"error".into(),message:Some(msg.clone()),..Default::default()});return Err(msg)}};match parse_model(&v){Ok(model)=>{set_download_state(&app,ModelDownloadState{active:false,phase:"completed".into(),percent:Some(100.0),..Default::default()});Ok(model)},Err(e)=>{set_download_state(&app,ModelDownloadState{active:false,phase:"error".into(),message:Some(e.clone()),..Default::default()});Err(e)}}}
#[tauri::command] fn model_status()->Result<ModelStatus,String>{model_action("status")}
#[tauri::command] async fn install_model(app:tauri::AppHandle)->Result<ModelStatus,String>{tauri::async_runtime::spawn_blocking(move||install_model_stream(app)).await.map_err(|e|format!("模型下載工作失敗: {e}"))?}
#[tauri::command] fn remove_model()->Result<ModelStatus,String>{model_action("remove")}
#[tauri::command] fn app_version()->&'static str{env!("CARGO_PKG_VERSION")}
#[cfg_attr(mobile,tauri::mobile_entry_point)] pub fn run(){tauri::Builder::default().invoke_handler(tauri::generate_handler![hardware_status,generate_image,model_status,model_download_status,install_model,remove_model,app_version]).run(tauri::generate_context!()).expect("error while running AI Studio");}